//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace trainingCenter
{
    using System;
    using System.Collections.Generic;
    
    public partial class Instructor_Attendence
    {
        public int Instructor_Attendance_ID { get; set; }
        public int Instructor_ID { get; set; }
        public Nullable<System.DateTime> Start_Time { get; set; }
        public Nullable<System.DateTime> End_Time { get; set; }
        public System.DateTime Day { get; set; }
        public int Room_ID { get; set; }
        public Nullable<double> Cost { get; set; }
        public Nullable<double> Discount { get; set; }
    
        public virtual Instructor Instructor { get; set; }
    }
}
