//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace trainingCenter
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_Group
    {
        public int StID_GID_ID { get; set; }
        public int G_ID { get; set; }
        public int St_ID { get; set; }
        public string Payment_Method { get; set; }
        public Nullable<double> St_Balance { get; set; }
    
        public virtual GroupName GroupName { get; set; }
        public virtual GroupName GroupName1 { get; set; }
        public virtual Student Student { get; set; }
        public virtual Student Student1 { get; set; }
    }
}
