//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace trainingCenter
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_Phones
    {
        public string ID_Stu { get; set; }
        public string Phone_Stu { get; set; }
        public string Phone2_Stu { get; set; }
        public string Phone3_Stu { get; set; }
    }
}
