//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace trainingCenter
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_Addresses
    {
        public string ID_Stud { get; set; }
        public string Address_Stu { get; set; }
        public string Address2_Stu { get; set; }
        public string Address3_Stu { get; set; }
    }
}
