//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace trainingCenter
{
    using System;
    using System.Collections.Generic;
    
    public partial class Total_Transaction
    {
        public int ID { get; set; }
        public Nullable<int> Person_ID { get; set; }
        public string Name { get; set; }
        public Nullable<double> Price { get; set; }
        public string Transaction_Type { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
