//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace trainingCenter
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Attend
    {
        public int User_ID { get; set; }
        public Nullable<System.DateTime> Attend_Time { get; set; }
        public Nullable<System.DateTime> Leave_Time { get; set; }
    
        public virtual User User { get; set; }
    }
}
